version: "3.8"
services:
  mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - 27017:27017
      volumes:
        - mongodata:/data
      environment:
        - MONGO_INIT_ROOT_USERNAME=admin
        - MONGO_INIT_ROOT_PASSWORD=admin
  redis:
      image: 'bitnami/redis:latest'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      restart: always
      ports:
        - 6379:6379
      volumes:
        - redisdata:/data
  elasticsearch:
      container_name: es-container
      image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
      environment:
#        - xpack.sercurity.enable=false
        - "discovery.type=single-node"
        - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
        - bootstrap.memory_lock=true
      ports:
        - 9200:9200
      volumes:
        - esdata:/data
volumes:
  mongodata:
    driver_opts:
      device: /home/hungnguyen/Documents/Learning Data/Thesis/travel-social-network/travel-social-network-data/mongodb
      o: bind
      type: tmpfs
  redisdata:
    driver_opts:
      device: /home/hungnguyen/Documents/Learning Data/Thesis/travel-social-network/travel-social-network-data/redis
      o: bind
      type: tmpfs
  esdata:
    driver_opts:
      device: /home/hungnguyen/Documents/Learning Data/Thesis/travel-social-network/travel-social-network-data/elasticsearch
      o: bind
      type: tmpfs
networks:
  default:
    name: travel-social-network