version: "3.8"
services:
  mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - 27017:27017
      volumes:
        - data:/data
      environment:
        - MONGO_INIT_ROOT_USERNAME=admin
        - MONGO_INIT_ROOT_PASSWORD=admin
  mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - 3300:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
        ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
        ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
volumes:
  data: {}
networks:
  default:
    name: mongodb_network